stages:
  - PEP8
  - tests

flake8:
  image: python:3-slim
  stage: PEP8
  before_script:
    - pip install flake8
  script:
    - flake8 . --config=.flake8
  tags:
    - docker-runner

tests:
  image: python:3-slim
  stage: tests
  before_script:
    - pip install .
  script:
    - python -m unittest -b
  tags:
    - docker-runner
