stages:
  - quality
  - tests

format check:
  image: python:3-slim
  stage: quality
  before_script:
    - pip install black
  script:
    - black src/ tests/ --check
  tags:
    - docker-runner

flake8:
  image: python:3-slim
  stage: quality
  before_script:
    - pip install flake8
  script:
    - flake8 . --config=.flake8
  tags:
    - docker-runner

tests:
  image: python:3-slim
  stage: tests
  before_script:
    - pip install ".[dev]"
  script:
    - ./run_tests
  tags:
    - docker-runner
