name: Test hmg

on: [push]

jobs:
  build:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.8", "3.9"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/checkout@v2
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare Environment
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Format Check
        run: |
          make format-check
      - name: PEP8
        run: |
          make flake8
      - name: unit tests
        run: |
          make tests
